name: champion_selector
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  shared_preferences: ^0.5.4+6
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  line_awesome_icons: ^1.0.4+2
  font_awesome_flutter: ^8.8.1
  vertical_navigation_bar: ^0.0.2
  device_preview: ^0.4.8
  process_run: ^0.11.0+2
  flutter_spinkit: "^4.1.2"
  autocomplete_textfield: ^1.6.4
  path_provider: ^1.6.21

dev_dependencies:
  flutter_test:
    sdk: flutter
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  assets:
    - assets/
    - assets/icons/
    - fetch_scripts/
    # - fetch_scripts/fetch_champions.py
    # - fetch_scripts/fetch_data.py
    - python/
    - python/asyncio/
    - python/certifi/
    - python/certifi/__pycache__/
    - python/chardet/
    - python/chardet/cli/
    - python/chardet/cli/__pycache__/
    - python/chardet/__pycache__/
    - python/collections/
    - python/concurrent/
    - python/concurrent/futures/
    - python/ctypes/
    - python/ctypes/macholib/
    - python/curses/
    - python/dbm/
    - python/distutils/
    - python/distutils/command/
    - python/email/
    - python/email/mime/
    - python/encodings/
    - python/html/
    - python/http/
    - python/idna/
    - python/idna/__pycache__/
    - python/importlib/
    - python/json/
    - python/Lib/
    - python/Lib/site-packages/
    - python/Lib/site-packages/pip/
    - python/Lib/site-packages/pip/_internal/
    - python/Lib/site-packages/pip/_internal/cli/
    - python/Lib/site-packages/pip/_internal/cli/__pycache__/
    - python/Lib/site-packages/pip/_internal/commands/
    - python/Lib/site-packages/pip/_internal/commands/__pycache__/
    - python/Lib/site-packages/pip/_internal/distributions/
    - python/Lib/site-packages/pip/_internal/distributions/__pycache__/
    - python/Lib/site-packages/pip/_internal/index/
    - python/Lib/site-packages/pip/_internal/index/__pycache__/
    - python/Lib/site-packages/pip/_internal/models/
    - python/Lib/site-packages/pip/_internal/models/__pycache__/
    - python/Lib/site-packages/pip/_internal/network/
    - python/Lib/site-packages/pip/_internal/network/__pycache__/
    - python/Lib/site-packages/pip/_internal/operations/
    - python/Lib/site-packages/pip/_internal/operations/build/
    - python/Lib/site-packages/pip/_internal/operations/build/__pycache__/
    - python/Lib/site-packages/pip/_internal/operations/install/
    - python/Lib/site-packages/pip/_internal/operations/install/__pycache__/
    - python/Lib/site-packages/pip/_internal/operations/__pycache__/
    - python/Lib/site-packages/pip/_internal/req/
    - python/Lib/site-packages/pip/_internal/req/__pycache__/
    - python/Lib/site-packages/pip/_internal/resolution/
    - python/Lib/site-packages/pip/_internal/resolution/legacy/
    - python/Lib/site-packages/pip/_internal/resolution/legacy/__pycache__/
    - python/Lib/site-packages/pip/_internal/resolution/resolvelib/
    - python/Lib/site-packages/pip/_internal/resolution/resolvelib/__pycache__/
    - python/Lib/site-packages/pip/_internal/resolution/__pycache__/
    - python/Lib/site-packages/pip/_internal/utils/
    - python/Lib/site-packages/pip/_internal/utils/__pycache__/
    - python/Lib/site-packages/pip/_internal/vcs/
    - python/Lib/site-packages/pip/_internal/vcs/__pycache__/
    - python/Lib/site-packages/pip/_internal/__pycache__/
    - python/Lib/site-packages/pip/_vendor/
    - python/Lib/site-packages/pip/_vendor/cachecontrol/
    - python/Lib/site-packages/pip/_vendor/cachecontrol/caches/
    - python/Lib/site-packages/pip/_vendor/cachecontrol/caches/__pycache__/
    - python/Lib/site-packages/pip/_vendor/cachecontrol/__pycache__/
    - python/Lib/site-packages/pip/_vendor/certifi/
    - python/Lib/site-packages/pip/_vendor/certifi/__pycache__/
    - python/Lib/site-packages/pip/_vendor/chardet/
    - python/Lib/site-packages/pip/_vendor/chardet/cli/
    - python/Lib/site-packages/pip/_vendor/chardet/cli/__pycache__/
    - python/Lib/site-packages/pip/_vendor/chardet/__pycache__/
    - python/Lib/site-packages/pip/_vendor/colorama/
    - python/Lib/site-packages/pip/_vendor/colorama/__pycache__/
    - python/Lib/site-packages/pip/_vendor/distlib/
    - python/Lib/site-packages/pip/_vendor/distlib/_backport/
    - python/Lib/site-packages/pip/_vendor/distlib/_backport/__pycache__/
    - python/Lib/site-packages/pip/_vendor/distlib/__pycache__/
    - python/Lib/site-packages/pip/_vendor/html5lib/
    - python/Lib/site-packages/pip/_vendor/html5lib/filters/
    - python/Lib/site-packages/pip/_vendor/html5lib/filters/__pycache__/
    - python/Lib/site-packages/pip/_vendor/html5lib/treeadapters/
    - python/Lib/site-packages/pip/_vendor/html5lib/treeadapters/__pycache__/
    - python/Lib/site-packages/pip/_vendor/html5lib/treebuilders/
    - python/Lib/site-packages/pip/_vendor/html5lib/treebuilders/__pycache__/
    - python/Lib/site-packages/pip/_vendor/html5lib/treewalkers/
    - python/Lib/site-packages/pip/_vendor/html5lib/treewalkers/__pycache__/
    - python/Lib/site-packages/pip/_vendor/html5lib/_trie/
    - python/Lib/site-packages/pip/_vendor/html5lib/_trie/__pycache__/
    - python/Lib/site-packages/pip/_vendor/html5lib/__pycache__/
    - python/Lib/site-packages/pip/_vendor/idna/
    - python/Lib/site-packages/pip/_vendor/idna/__pycache__/
    - python/Lib/site-packages/pip/_vendor/msgpack/
    - python/Lib/site-packages/pip/_vendor/msgpack/__pycache__/
    - python/Lib/site-packages/pip/_vendor/packaging/
    - python/Lib/site-packages/pip/_vendor/packaging/__pycache__/
    - python/Lib/site-packages/pip/_vendor/pep517/
    - python/Lib/site-packages/pip/_vendor/pep517/__pycache__/
    - python/Lib/site-packages/pip/_vendor/pkg_resources/
    - python/Lib/site-packages/pip/_vendor/pkg_resources/__pycache__/
    - python/Lib/site-packages/pip/_vendor/progress/
    - python/Lib/site-packages/pip/_vendor/progress/__pycache__/
    - python/Lib/site-packages/pip/_vendor/requests/
    - python/Lib/site-packages/pip/_vendor/requests/__pycache__/
    - python/Lib/site-packages/pip/_vendor/resolvelib/
    - python/Lib/site-packages/pip/_vendor/resolvelib/compat/
    - python/Lib/site-packages/pip/_vendor/resolvelib/compat/__pycache__/
    - python/Lib/site-packages/pip/_vendor/resolvelib/__pycache__/
    - python/Lib/site-packages/pip/_vendor/toml/
    - python/Lib/site-packages/pip/_vendor/toml/__pycache__/
    - python/Lib/site-packages/pip/_vendor/urllib3/
    - python/Lib/site-packages/pip/_vendor/urllib3/contrib/
    - python/Lib/site-packages/pip/_vendor/urllib3/contrib/_securetransport/
    - python/Lib/site-packages/pip/_vendor/urllib3/contrib/_securetransport/__pycache__/
    - python/Lib/site-packages/pip/_vendor/urllib3/contrib/__pycache__/
    - python/Lib/site-packages/pip/_vendor/urllib3/packages/
    - python/Lib/site-packages/pip/_vendor/urllib3/packages/backports/
    - python/Lib/site-packages/pip/_vendor/urllib3/packages/backports/__pycache__/
    - python/Lib/site-packages/pip/_vendor/urllib3/packages/ssl_match_hostname/
    - python/Lib/site-packages/pip/_vendor/urllib3/packages/ssl_match_hostname/__pycache__/
    - python/Lib/site-packages/pip/_vendor/urllib3/packages/__pycache__/
    - python/Lib/site-packages/pip/_vendor/urllib3/util/
    - python/Lib/site-packages/pip/_vendor/urllib3/util/__pycache__/
    - python/Lib/site-packages/pip/_vendor/urllib3/__pycache__/
    - python/Lib/site-packages/pip/_vendor/webencodings/
    - python/Lib/site-packages/pip/_vendor/webencodings/__pycache__/
    - python/Lib/site-packages/pip/_vendor/__pycache__/
    - python/Lib/site-packages/pip/__pycache__/
    - python/Lib/site-packages/pip-20.2.3.dist-info/
    - python/Lib/site-packages/pkg_resources/
    - python/Lib/site-packages/pkg_resources/extern/
    - python/Lib/site-packages/pkg_resources/extern/__pycache__/
    - python/Lib/site-packages/pkg_resources/_vendor/
    - python/Lib/site-packages/pkg_resources/_vendor/packaging/
    - python/Lib/site-packages/pkg_resources/_vendor/packaging/__pycache__/
    - python/Lib/site-packages/pkg_resources/_vendor/__pycache__/
    - python/Lib/site-packages/pkg_resources/__pycache__/
    - python/Lib/site-packages/setuptools/
    - python/Lib/site-packages/setuptools/command/
    - python/Lib/site-packages/setuptools/command/__pycache__/
    - python/Lib/site-packages/setuptools/extern/
    - python/Lib/site-packages/setuptools/extern/__pycache__/
    - python/Lib/site-packages/setuptools/_distutils/
    - python/Lib/site-packages/setuptools/_distutils/command/
    - python/Lib/site-packages/setuptools/_distutils/command/__pycache__/
    - python/Lib/site-packages/setuptools/_distutils/__pycache__/
    - python/Lib/site-packages/setuptools/_vendor/
    - python/Lib/site-packages/setuptools/_vendor/packaging/
    - python/Lib/site-packages/setuptools/_vendor/packaging/__pycache__/
    - python/Lib/site-packages/setuptools/_vendor/__pycache__/
    - python/Lib/site-packages/setuptools/__pycache__/
    - python/Lib/site-packages/setuptools-50.3.0.dist-info/
    - python/Lib/site-packages/wheel/
    - python/Lib/site-packages/wheel/cli/
    - python/Lib/site-packages/wheel/cli/__pycache__/
    - python/Lib/site-packages/wheel/vendored/
    - python/Lib/site-packages/wheel/vendored/packaging/
    - python/Lib/site-packages/wheel/vendored/packaging/__pycache__/
    - python/Lib/site-packages/wheel/vendored/__pycache__/
    - python/Lib/site-packages/wheel/__pycache__/
    - python/Lib/site-packages/wheel-0.35.1.dist-info/
    - python/Lib/site-packages/_distutils_hack/
    - python/Lib/site-packages/_distutils_hack/__pycache__/
    - python/Lib/site-packages/__pycache__/
    - python/lib2to3/
    - python/lib2to3/fixes/
    - python/lib2to3/pgen2/
    - python/logging/
    - python/msilib/
    - python/multiprocessing/
    - python/multiprocessing/dummy/
    - python/pydoc_data/
    - python/requests/
    - python/requests/__pycache__/
    - python/Scripts/
    - python/site-packages/
    - python/sqlite3/
    - python/unittest/
    - python/urllib/
    - python/urllib3/
    - python/urllib3/contrib/
    - python/urllib3/contrib/_securetransport/
    - python/urllib3/contrib/_securetransport/__pycache__/
    - python/urllib3/contrib/__pycache__/
    - python/urllib3/packages/
    - python/urllib3/packages/backports/
    - python/urllib3/packages/backports/__pycache__/
    - python/urllib3/packages/ssl_match_hostname/
    - python/urllib3/packages/ssl_match_hostname/__pycache__/
    - python/urllib3/packages/__pycache__/
    - python/urllib3/util/
    - python/urllib3/util/__pycache__/
    - python/urllib3/__pycache__/
    - python/wsgiref/
    - python/xml/
    - python/xml/dom/
    - python/xml/etree/
    - python/xml/parsers/
    - python/xml/sax/
    - python/xmlrpc/


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

